homepage:
    path: /index
    defaults: { _controller: FacturaBundle:Default:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
  
FacturaBundle_detalle:
    resource: "@FacturaBundle/Resources/config/routing/detalle.yml"
    prefix:   /detalle   
    
FacturaBundle_condicion_pago:
    resource: "@FacturaBundle/Resources/config/routing/condicionpago.yml"
    prefix:   /condicionpago  
 
FacturaBundle_iva:
    resource: "@FacturaBundle/Resources/config/routing/iva.yml"
    prefix:   /iva
    
FacturaBundle_localidad:
    resource: "@FacturaBundle/Resources/config/routing/localidad.yml"
    prefix:   /localidad
    
FacturaBundle_producto:
    resource: "@FacturaBundle/Resources/config/routing/producto.yml"
    prefix:   /producto
    
FacturaBundle_proveedor:
    resource: "@FacturaBundle/Resources/config/routing/proveedor.yml"
    prefix:   /proveedor
    
FacturaBundle_provincia:
    resource: "@FacturaBundle/Resources/config/routing/provincia.yml"
    prefix:   /provincia
    
FacturaBundle_factura:
    resource: "@FacturaBundle/Resources/config/routing/factura.yml"
    prefix:   /factura

login_check:
  pattern: /login_check

logout:
  pattern: /logout

