parameters:
#    factura.example.class: Witzke\FacturaBundle\Example

services:
#    factura.example:
#        class: %factura.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
