parameters:
#    factura.example.class: Witzke\FacturaBundle\Example

services:
#    factura.example:
#        class: %factura.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

     factura.buscador:
        class: Witzke\FacturaBundle\Services\BuscadorFactura
        arguments: [@doctrine.orm.entity_manager]
