localidad:
    path:     /
    defaults: { _controller: "FacturaBundle:Localidad:index" }

localidad_show:
    path:     /{id}/show
    defaults: { _controller: "FacturaBundle:Localidad:show" }

localidad_new:
    path:     /new
    defaults: { _controller: "FacturaBundle:Localidad:new" }

localidad_create:
    path:     /create
    defaults: { _controller: "FacturaBundle:Localidad:create" }
    requirements: { _method: post }

localidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "FacturaBundle:Localidad:edit" }

localidad_update:
    path:     /{id}/update
    defaults: { _controller: "FacturaBundle:Localidad:update" }
    requirements: { _method: post|put }

localidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "FacturaBundle:Localidad:delete" }
    requirements: { _method: post|delete }
    
seleccionar_localidad:
    pattern: /seleccionar
    defaults: { _controller: 'FacturaBundle:Localidad:seleccionar' }
