<?php

namespace Witzke\FacturaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IvaRepository extends EntityRepository
{
}
