<?php

namespace Witzke\FacturaBundle\Entity\Repository;
use Witzke\FacturaBundle\Entity\Localidad;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciaRepository extends EntityRepository {

    public function findByLocalidadId($localidad_id) {
        $query = $this->getEntityManager()->createQuery("
SELECT provincia
FROM ReclamosBundle:Provincia provincia
LEFT JOIN provincia.localidad localidad
WHERE localidad.id = :localidad_id
")->setParameter('localidad_id', $localidad_id);
        return $query->getResult();
    }

}
